### ISSUE TITLE
function names cannot contain "def" as prefix

### ISSUE THREAD

**Issue by bowenwang1996** [ravichugh/sketch-n-sketch#109]
If we try to define a function whose name contains "def" as a prefix, the parser will throw a 
`Error while parsing 'top-level non-recursive def binding'`

For example,  `(def defaultId (\x x))
(defaultId 1)` causes the parse error mentioned above.

**Comment by MikaelMayer** [comment]
We are soon switching to a different syntax. We will probably not fix this issue. But thanks for reporting.
