### ISSUE TITLE
Misc Deuce TODOs

### ISSUE THREAD

**Issue by ravichugh** [ravichugh/sketch-n-sketch#110]
- X button in pop-up windows (deuce, right-click, config panel).

- Restore Deuce selection state on Undo.

- Issue with text-selection. Hold Shift and press an arrow key to perform an Ace text selection. A Deuce polygon appears.

- (let p e1 e2) target positions: The whitespace between p and e1 is treated specially, with all characters up to the first newline (if any) dedicated to after-p, and the rest to before-e1. Instead, each polygon should be mapped to a set of code objects (specifically, white space objects in this case), and selection sets should be interpreted as the Cartesian product of the selected code object sets.

**Comment by jlubi333** [comment]
Moved to individual issues in project board.
