### ISSUE TITLE
FastParser performance issues

### ISSUE THREAD

**Issue by ravichugh** [ravichugh/sketch-n-sketch#122]
Here's a series of small examples that demonstrate FastParser performance issues. Try running the program `[]`, then `[[]]`, then `[[[]]]`, etc., viewing the "FastParser.parseE milliseconds" output in the console.

The numbers I got (in milliseconds) are listed below.

I tried moving `lazy <| \_ -> list` (FastParser line 1278) higher up in the oneOf list. This improves performance only slightly; the last example below runs in 48s instead of 61s.

```
[
]

2

[[
]]

3

[[[
]]]

7

[[[[
]]]]

16

[[[[[
]]]]]

25

[[[[[[
]]]]]]

50

[[[[[[[
]]]]]]]

93

[[[[[[[[
]]]]]]]]

190

[[[[[[[[[
]]]]]]]]]

361

[[[[[[[[[[
]]]]]]]]]]

727

[[[[[[[[[[[
]]]]]]]]]]]

1482

[[[[[[[[[[[[
]]]]]]]]]]]]

3044

[[[[[[[[[[[[[
]]]]]]]]]]]]]

6264

[[[[[[[[[[[[[[
]]]]]]]]]]]]]]

14621

[[[[[[[[[[[[[[[
]]]]]]]]]]]]]]]

29158

[[[[[[[[[[[[[[[[
]]]]]]]]]]]]]]]]

61183



```

**Comment by MikaelMayer** [comment]
Hello Ravi, is it still an issue?
I think this comes from the fact that we are "trying" parsers for parsing lists, and this leads to an exponential complexity.
What I think we should do is to accept the "[", parse as many elements as possible, and possibly end with the | operator (we still have multi-cons in the parser)
"try" should be avoided as much as possible.

**Comment by MikaelMayer** [comment]
I cannot reproduce it with the latest FastParser. I bet this had been fixed.
