### ISSUE TITLE
Relate menu preview freeze the application

### ISSUE THREAD

**Issue by MikaelMayer** [ravichugh/sketch-n-sketch#123]
I tried to create a logo using Sketch'n Sketch (on the branch value-editor, but it's not important I think)
The logo is composed of a black rectangle on the left and a white rectangle on the right, with yellow lines on the black rectangle.
At some point I wanted to align the right sides of the yellow rectangles by making them equal, I hold shift, selected two alignments, and went to the menu to make them equal. When the menu opened, I accidentally went on "Relate" and it made  the whole application to freeze.

I may have accidentally selected one more element. But freezing the application is still a bug. What part of Sketch'n Sketch should I investigate to resolve this potential bug?

![image](https://user-images.githubusercontent.com/3601079/34425694-0c4c77d4-ebf4-11e7-83c3-13d0b843d05b.png)

**Comment by brianhempel** [comment]
Relate is just slow: it does arithmetic term enumeration, which is exponential time.

For only three selected things, it should terminate within a minute. But yes: it's slow and may be revisited in the future.
