### ISSUE TITLE
entering edit mode inserts an e

### ISSUE THREAD

**Issue by cfbolz** [ravichugh/sketch-n-sketch#43]
When the canvas is active (with the fancy code box) entering edit mode by pressing 'e' works, but then the 'e' is also inserted. I would expect that not to happen (and it's quite annoying). Using Chrome Version 44.0.2403.89 Ubuntu 15.04 (64-bit)

**Comment by mhspradlin** [comment]
This appears to be fixed after merging #44 - The 0.3 release has not been updated, but this will be included in the next stable release.
