### ISSUE TITLE
Firefox 43.0.4, Ubuntu 64 bit: Runtime Error too much recursion

### ISSUE THREAD

**Issue by berndca** [ravichugh/sketch-n-sketch#56]
When I open https://ravichugh.github.io/sketch-n-sketch/releases/v0.4/ in Firefox 43 I get the following message:

```
too much recursion
Open the developer console for more details.
```

BTW, the script tag should appear **inside** the body tag in index.html.

---

_Ed. note:_ Same as #84.

**Comment by kriswill** [comment]
"Maximum call stack exceeded" on iOS with Safari and chrome.

**Comment by brianhempel** [comment]
Ah, yes. I can reproduce on Ubuntu 12 with Firefox 43. Firefox 43 on Mac OS X is fine, however. (As is Chrome and Safari on OS X.) Maybe they have different recursion limits?

**Comment by n1k0** [comment]
Confirmed

![](http://i.imgur.com/xgZc89T.png)

**Comment by brianhempel** [comment]
The [v0.4.1 release](http://ravichugh.github.io/sketch-n-sketch/releases/v0.4.1/) was compiled with Elm 16 and that appears to have fixed the issue for Ubuntu Firefox

Still need to check iOS.

**Comment by kasbah** [comment]
I am getting this issue on the v0.5 demo but not on v0.4.2. Firefox Ubuntu 64-bit.

**Comment by iqualfragile** [comment]
still getting this on v5. it does work on v4.
firefox 48.

**Comment by eriknstr** [comment]
>too much recursion
>
>Open the developer console for more details.

when opening [v0.5.2](http://ravichugh.github.io/sketch-n-sketch/releases/v0.5.2/) in Firefox 49.0 on Fedora 23.

Meanwhile, [v0.4.2](http://ravichugh.github.io/sketch-n-sketch/releases/v0.4.2/) works.

**Comment by jlubi333** [comment]
Migrating this issue to #84.
