### ISSUE TITLE
[Feature request] Make clicking on the editor/canvas switch between "Edit/Run Code"

### ISSUE THREAD

**Issue by JobLeonard** [ravichugh/sketch-n-sketch#58]
Even in the demo videos I've seen a few "oops, forgot to click the 'edit code'-button" moments, and you *designed* the program ;)

As far as I can see, there is no ambiguity of intent when clicking on either side, so why not remove the need for a superfluous click on the run/edit code button? This would reduce the "friction" of the editing experience even further!

(note: I'm not suggesting that the button is removed, because it is not immediately obvious that clicking on either side would switch)

**Comment by brianhempel** [comment]
Thanks for the feature request. It's definitely on our todo list.

**Comment by brianhempel** [comment]
We've made the code always-editable (on the master branch, not deployed yet).
