### ISSUE TITLE
demo looks wrong on Mac Firefox

### ISSUE THREAD

**Issue by raould** [ravichugh/sketch-n-sketch#59]
Mac OS X 10.10.5
Firefox 39.0
text chopped off in various places?
http://imagebin.ca/v/2WISxDzZFNr9

**Comment by ravichugh** [comment]
Thanks for pointing this out. Does the following work better on your system?

[http://ravichugh.github.io/sketch-n-sketch/releases/v0.4.1/](http://ravichugh.github.io/sketch-n-sketch/releases/v0.4.1/)

**Comment by raould** [comment]
Looks the same. It seems to be something about text wrapping? Like the strings are too long to fit in their button areas?

**Comment by ravichugh** [comment]
Just tweaked the default font sizes. Try again?

[http://ravichugh.github.io/sketch-n-sketch/releases/v0.4.1/](http://ravichugh.github.io/sketch-n-sketch/releases/v0.4.1/)

**Comment by raould** [comment]
WORKS. :-)
