### ISSUE TITLE
Shape tool not mutually exclusive with other modes

### ISSUE THREAD

**Issue by brianhempel** [ravichugh/sketch-n-sketch#70]
![shape_tools_bug](https://cloud.githubusercontent.com/assets/506950/14001827/1f71d244-f116-11e5-8656-35e8311d0415.gif)

Maybe lean on the type system?

Also, polygon tool seems to sometimes be offset from the mouse position. Triggering a window resize event fixes the problem.

**Comment by ravichugh** [comment]
Oops, bug introduced with my recent changes. Try now.

**Comment by brianhempel** [comment]
Seems to be working.
