### ISSUE TITLE
Can't delete in save dialog

### ISSUE THREAD

**Issue by brianhempel** [ravichugh/sketch-n-sketch#71]
This typo will exist indefinitely in local storage! :)

![screen shot 2016-03-24 at 9 25 40 am](https://cloud.githubusercontent.com/assets/506950/14019815/836f18c4-f1a2-11e5-9660-9b1b977b3529.png)

**Comment by ravichugh** [comment]
I've undone the keys events for now.

**Comment by brianhempel** [comment]
Now the clone dialog is covered by the code box. Probably my doing; just leaving this here to log the bug.

![screen shot 2016-09-19 at 10 40 27 am](https://cloud.githubusercontent.com/assets/506950/18638380/8521a426-7e55-11e6-95eb-c7f1dae0a910.png)

**Comment by ravichugh** [comment]
Local storage features/UI have been overhauled.
