### ISSUE TITLE
Source code for tutorials

### ISSUE THREAD

**Issue by Seanny123** [ravichugh/sketch-n-sketch#97]
Where is the source code for the Sketch-n-Sketch tutorials? They're out of date and I would like to propose some amendments to them.

Additionally, there is no longer a drop-down for the examples.

**Comment by jlubi333** [comment]
Which tutorials are you referring to exactly? Also, when you create a new file, you should have a list of "templates"—these are exactly the example files from previous versions.

**Comment by Seanny123** [comment]
I am referring to the tutorials found at https://ravichugh.github.io/sketch-n-sketch/tutorial/01.html

**Comment by jlubi333** [comment]
I don't believe there is source code for those tutorials. Another thing that we'd love to work on at some point is a more robust tutorial system (possibly built into the app). In the meantime, any contributions to improving the tutorials would be very welcomed!

**Comment by Seanny123** [comment]
In the interest of clarity, I guess I should specify that by "source code", I also meant the Markdown files that generated those pages. It seems attaches to a `github.io` domain name, so I'm assuming they're from a private repository?

**Comment by jlubi333** [comment]
Ah, my apologies. Yes, I believe that is a private repository.

**Comment by Seanny123** [comment]
Cool. Let me know if you have any motivation to make it public. I can help if you send me the files. :D

**Comment by brianhempel** [comment]
The tutorials are on the `gh-pages` branch. You can modify them locally and submit requests as normal.
